# Use root/example as user/password credentials
version: '3.1'

services:

  mongo-python-test:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  python-test-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on: 
      - mongo-python-test